### ISSUE TITLE
Erroneous Insufficient Balance 

### ISSUE THREAD

**Issue by lucadgtrip** [OriginProtocol/origin#2514]
in https://dapp.tripscommunity.com/#/listing/1-000-2781
I set some dates and got a 2.087 ETH price.
In my metamask I have 3.4 ETH
still, I am not able to make the purchase.
The system does not seem to see the money.

On Mac Osx, Chrome

![Screenshot 2019-06-24 at 10 39 29](https://user-images.githubusercontent.com/34341206/60000455-ef7b9980-966c-11e9-9d9e-28dfed184fd1.png)
![Screenshot 2019-06-24 at 10 39 16](https://user-images.githubusercontent.com/34341206/60000456-ef7b9980-966c-11e9-86e4-074bdda0ffa2.png)

**Comment by micahalcorn** [comment]
Thanks @lucadgtrip 😕 Did you already have the funds in your wallet when you loaded this page? Did it do any good to refresh it, or are you still unable to get past this message?

**Comment by lucadgtrip** [comment]
yes, the funds were in since long time (0x36666e1fdC526f6df4638491F087e907A542BCdf).
I just tried again and it's still stuck at this point

**Comment by micahalcorn** [comment]
Should be fixed by https://github.com/OriginProtocol/origin/pull/2520 🤞

**Comment by lucadgtrip** [comment]
![Screenshot 2019-06-26 at 19 34 53](https://user-images.githubusercontent.com/34341206/60198116-8dc45680-9849-11e9-9d71-c2e652c79b21.png)
still not working for me.
Any suggestions?

**Comment by micahalcorn** [comment]
@lucadgtrip try on staging/rinkeby. I don't think we have deployed the fix to mainnet/production yet. 🙂

**Comment by lucadgtrip** [comment]
ok works there, thanks
