### ISSUE TITLE
Single Accepted Currency

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3761]
If only one currency is accepted for a given listing, there is no indication for what is accepted. I think we should potentially just skip this screen if the buyer has sufficient funds and cannot make any selection here. We will still need to show this screen in cases where there is no selection for the buyer to make but she has insufficient funds.

![77721556-AF02-40E0-A2A6-CEC1A945BC28](https://user-images.githubusercontent.com/273937/67254654-1edfbe80-f433-11e9-9c88-dc5e9437e5c7.png)

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by shahthepro** [comment]
@micahalcorn Can you share the listing ID on which you could reproduce this? I want have a quick look on the IPFS hash. Unless you don't have the `acceptedTokens` field in the IPFS data, you should see the tokens listed here on this screen.

**Comment by micahalcorn** [comment]
I think this was https://dapp.staging.originprotocol.com/#/listing/4-000-383 @shahthepro. 😐

**Comment by shahthepro** [comment]
@micahalcorn 

Yep, it doesn't have the `acceptedTokens` array set as I suspected. Could be a really old listing. Updating the listing should fix this. 

<img width="738" alt="Screenshot 2019-10-22 at 8 17 31 AM" src="https://user-images.githubusercontent.com/10547529/67256403-6f433480-f4a4-11e9-96bb-2a88981ce0eb.png">

As for skipping the screen when the user has sufficient funds and seller accepts only one screen, will work on that.

**Comment by micahalcorn** [comment]
I've confirmed that updating the listing resolves the funky visuals. For the record, updating it does not resolve https://github.com/OriginProtocol/origin/issues/3762. 😐

**Comment by micahalcorn** [comment]
Deprioritizing this one for now 👎 I think it's debatable whether or not we should show this step in the simple case of the seller only accepting one and the buyer having enough of it. Ideally, we also would be backward-compatible with this screen so that older listings work as intended, but it's not a big deal.

**Comment by micahalcorn** [comment]
@shahthepro here are the rules that I think we should follow:

- Only one accepted currency: it should be auto-selected, this screen should be displayed, and the buyer should have to click continue (one click).
- More than one accepted currency: no auto-selection should be made regardless of whether or not the buyer has sufficient funds for any particular one (two clicks).

🤔
