### ISSUE TITLE
English specific phrase contractions

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin#566]
We assemble an English phrase, e.g. "Finalized on Sep 9, 2019" by swapping in the verb and date and concatenating:

https://github.com/OriginProtocol/origin-dapp/blob/master/src/components/my-purchase-card.js#L107

In many languages this will be unlocalizable. We should assemble the entire sentence (and substitute in the date) where we currently select the verb, e.g. here:
https://github.com/OriginProtocol/origin-dapp/blob/master/src/components/my-purchase-card.js#L100

EDIT: Obviously not a priority for mainnet, but good to have in our backlog. 

Related: https://github.com/OriginProtocol/origin-dapp/issues/372

**Comment by micahalcorn** [comment]
Assuming this is resolved by the recent localization efforts 🙂

**Comment by wanderingstan** [comment]
Sorry, still an issue. 🙁

https://github.com/OriginProtocol/origin/blob/8694832f8e552ce6c476e29eb7c63816572a6b05/dapps/marketplace/src/pages/messaging/Room.js#L20-L31

**Comment by micahalcorn** [comment]
Okay, thanks @wanderingstan 😐

**Comment by wanderingstan** [comment]
For future: 
What needs to be done is to create a  set of all complete sentences with fbt params. Doesn't matter if it's lot. E..g

```
`You made an offer on {productname} on {date}`,
`{name} made an offer on {productname} on {date}`,
`You accepted an offer on {productname} on {date}`,
`{name} accepted an offer on {productname} on {date}`,
`You withdrew an offer on {productname} on {date}`,
`{name} withdrew an offer on {productname} on {date}`,
...
```

Or whatever, with logic to select the right sentence template in each situation.
